# Generated by Django 2.1.7 on 2019-03-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indicios', '0002_auto_20190307_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicio',
            name='Fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicio',
            name='Hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
