# Generated by Django 2.1.7 on 2019-03-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indicios', '0003_auto_20190307_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicio',
            old_name='Deposita_Banco',
            new_name='Deposito_Banco',
        ),
        migrations.AlterField(
            model_name='indicio',
            name='Cadena',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No'), ('CS', 'Copia Simple'), ('CC', 'Copia Certificada')], default='S', max_length=2),
        ),
        migrations.AlterField(
            model_name='indicio',
            name='Clasificacion',
            field=models.CharField(choices=[('A', 'Arma de Fuego'), ('B', 'Arma Blanca'), ('D', 'Droga'), ('AL', 'Alcohol'), ('P', 'Perecedero'), ('E', 'Electronico'), ('AP', 'Autopartes'), ('H', 'Herramientas'), ('AB', ' Articulos de Belleza'), ('R', ' Ropa'), ('N', ' Numerario')], default='A', max_length=2),
        ),
        migrations.AlterField(
            model_name='indicio',
            name='Embalaje',
            field=models.CharField(choices=[('B', 'Bolsa de Plastico'), ('BP', 'Bolsa de Papel'), ('SB', 'Sobre Blanco'), ('SM', 'Sobre Manila'), ('O', 'Otro')], default='B', max_length=2),
        ),
    ]
