# Generated by Django 2.1.7 on 2019-03-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indicios', '0005_auto_20190307_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicio',
            name='Hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
