# Generated by Django 2.1.7 on 2019-03-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indicios', '0007_auto_20190307_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicio',
            name='Fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicio',
            name='Hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
