# Generated by Django 2.1.7 on 2019-03-07 19:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Indicios', '0008_auto_20190307_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicio',
            name='Ubicacion',
            field=models.CharField(default=django.utils.timezone.now, help_text='Ingrese ubicacion del indicio', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicio',
            name='userlogo',
            field=models.ImageField(blank=True, null=True, upload_to='userlogo/'),
        ),
    ]
