# Generated by Django 2.1.7 on 2019-03-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indicios', '0010_auto_20190307_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicio',
            old_name='Fecha',
            new_name='Fecha_Ingreso',
        ),
        migrations.RenameField(
            model_name='indicio',
            old_name='Hora',
            new_name='Hora_Ingreso',
        ),
        migrations.AddField(
            model_name='indicio',
            name='Estado_embalaje',
            field=models.CharField(choices=[('C', 'Cerrado'), ('A', 'Abierto'), ('AL', 'Alterado'), ('R', 'Roto'), ('O', 'Otro')], default='C', max_length=2),
        ),
        migrations.AddField(
            model_name='indicio',
            name='Observaciones',
            field=models.TextField(default=2, help_text='Aqui puede hacer observaciones del indicio y embalaje, entre otras', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indicio',
            name='Clasificacion',
            field=models.CharField(choices=[('AC', 'Arma de Fuego Corta'), ('AL', 'Arma de Fuego Larga'), ('AB', 'Arma Blanca'), ('EM', 'Estupefaciente-Marihuana'), ('EC', 'Estupefaciente-Cocaina'), ('EH', 'Estupefaciente-Heroina'), ('EA', 'Estupefaciente-Anfetamina'), ('ET', 'Estupefaciente-Tabaco'), ('AL', 'Alcohol'), ('P', 'Perecedero'), ('E', 'Electronico'), ('AP', 'Autopartes'), ('H', 'Herramientas'), ('AB', ' Articulos de Belleza'), ('J', 'Joyeria'), ('R', ' Ropa'), ('N', ' Numerario'), ('O', 'Otro')], default='A', max_length=2),
        ),
        migrations.AlterField(
            model_name='indicio',
            name='Embalaje',
            field=models.CharField(choices=[('B', 'Bolsa de Plastico'), ('BP', 'Bolsa de Papel'), ('SB', 'Sobre Blanco'), ('SM', 'Sobre Manila'), ('EM', 'Emplayado'), ('CJ', 'Caja de Carton'), ('SE', 'Sin Embalaje'), ('O', 'Otro')], default='B', max_length=2),
        ),
        migrations.AlterField(
            model_name='indicio',
            name='Tipo',
            field=models.CharField(choices=[('F', 'Fisico'), ('O', 'Organico'), ('B', 'Biologico'), ('M', 'Fisico/Organico')], default='F', max_length=1),
        ),
    ]
